sudo: required
dist: trusty
services: docker
branches:
  only:
  - master
branches:
  only:
  - master
script: 
  - wget https://github.com/tiulpin/xelatex-docker/raw/master/latexdockercmd.sh -O latexdockercmd.sh
  - chmod a+x latexdockercmd.sh
  - ./latexdockercmd.sh latexmk -cd -f -interaction=batchmode -pdf main.tex
  - mv main.pdf presentation-template.pdf
deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "presentation-template.pdf"
  skip_cleanup: true
  on:
    repo: iamm-templates/presentation-template
