dist: bionic
sudo: true

install:
  - sudo apt install texlive-full

script: 
  - latexmk -interaction=nonstopmode main.tex

deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  on:
    repo: iamm-templates/presentation-template
